<link rel="stylesheet" href="/assets/AdminLTE-2.4.5/bower_components/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="/assets/AdminLTE-2.4.5/bower_components/font-awesome/css/font-awesome.min.css" />
<link rel="stylesheet" href="/assets/AdminLTE-2.4.5/bower_components/Ionicons/css/ionicons.min.css" />
<link rel="stylesheet" href="/assets/AdminLTE-2.4.5/dist/css/AdminLTE.min.css" />
<link rel="stylesheet" href="/assets/AdminLTE-2.4.5/dist/css/skins/skin-green.min.css" />
<link rel="stylesheet" href="/assets/DataTables/datatables.min.css" />
<link rel="stylesheet" href="/assets/jquery-ui-1.12.1/jquery-ui.min.css" />
<link rel="stylesheet" href="/assets/css/app.css" />
<link rel="stylesheet" href="/assets/css/datatables.css" />